name: Publish Notes (Dev)

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/publish-dev-notes.yml'
      - 'src/**'
  workflow_dispatch:

jobs:
  notes-publish-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Prepare - Checkout Code
      uses: actions/checkout@v2
    -
      name: Prepare - Read image version
      uses: bfren/read-file@v1
      with:
        file: ./Version
      id: version
    -
      name: Prepare - Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Prepare - Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Prepare - Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Prepare - Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    -
      name: A - Publish
      run: |
        dotnet publish ./src/Strasnote.Notes.Api/Strasnote.Notes.Api.csproj \
          --configuration Release \
          --runtime linux-musl-x64 \
          --output ./publish \
          --no-self-contained
    -
      name: B - Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Strasnote.Notes.Api/Dockerfile-automated
        push: true
        platforms: linux/amd64
        tags: |
          strasnote/notes:dev
          strasnote/notes:${{ steps.version.outputs.content }}dev
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
