name: Publish Auth (Dev)

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/publish-dev-auth.yml'
      - 'src/**'
  workflow_dispatch:

jobs:
  auth-publish-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Prepare - Checkout Code
      uses: actions/checkout@v3
    -
      name: Prepare - Read image version
      uses: bfren/read-file@v2
      id: version
    -
      name: Prepare - Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Prepare - Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Prepare - Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Prepare - Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
    -
      name: A - Publish
      run: |
        dotnet publish src/Strasnote.Auth.Api/Strasnote.Auth.Api.csproj \
          --configuration Release \
          --output ./publish \
          --no-self-contained
    -
      name: B - Push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./src/Strasnote.Auth.Api/Dockerfile-automated
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: |
          strasnote/auth:dev
          strasnote/auth:${{ steps.version.outputs.contents }}dev
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
